const NARNIA = [
  {
    coordinates: {
      id: 'get-weather-error',
      lang: 'en',
      location: 'narnia',
      lat: 78.3891,
      long: -57.4824,
      timezone: 'America/New_York',
      timezone_offset: -14400,
      units: 'imperial',
    },
    current: {
      timestamp: 248400000,
      description: 'always winter',
      icon: '13d',
      temp: 20,
      high: 25,
      low: 15,
      feelsLike: 20,
      visibility: 6.2,
      precip: 100,
      dewPoint: 20,
      sunrise: 1000029600000,
      sunset: 1000072800000,
      uvIndex: 0,
      uvLevel: 'low',
      humidity: 96,
      windSpeed: 12,
      windDirection: 'W',
      windDeg: 280,
    },
    daily: [
      {
        timestamp: 1000086400000,
        description: 'snowfall',
        icon: '13d',
        high: 25,
        low: 15,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
      },
      {
        timestamp: 1000172800000,
        description: 'snowfall',
        icon: '13d',
        high: 25,
        low: 15,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
      },
      {
        timestamp: 1000259200000,
        description: 'snowfall',
        icon: '13d',
        high: 25,
        low: 15,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
      },
      {
        timestamp: 1000345600000,
        description: 'snowfall',
        icon: '13d',
        high: 25,
        low: 15,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
      },
      {
        timestamp: 1000432000000,
        description: 'snowfall',
        icon: '13d',
        high: 25,
        low: 15,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
      },
      {
        timestamp: 1000518400000,
        description: 'snowfall',
        icon: '13d',
        high: 25,
        low: 15,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
      },
      {
        timestamp: 1000604800000,
        description: 'snowfall',
        icon: '13d',
        high: 25,
        low: 15,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
      },
    ],
    hourly: [
      {
        timestamp: 1654549200000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654552800000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654556400000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654560000000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654563600000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654567200000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654570800000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654574400000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654578000000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654581600000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654585200000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654588800000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654592400000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654596000000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654599600000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654603200000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654606800000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654610400000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654614000000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654617600000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654621200000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654624800000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654628400000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654632000000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654635600000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654639200000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654642800000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654646400000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654650000000,
        description: '--',
        icon: '13d',
        temp: '--',
        precip: '--',
        humidity: '--',
        windSpeed: '--',
        windDirection: '--',
        windDeg: '--',
        uvIndex: '--',
        uvLevel: '--',
      },
      {
        timestamp: 1654653600000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654657200000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654660800000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654664400000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654668000000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654671600000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654675200000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654678800000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654682400000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654686000000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654689600000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654693200000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654696800000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654700400000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654704000000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654707600000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654711200000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654714800000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
      {
        timestamp: 1654718400000,
        description: 'snowfall',
        icon: '13d',
        temp: 25,
        precip: 100,
        humidity: 96,
        windSpeed: 12,
        windDirection: 'W',
        windDeg: 280,
        uvIndex: 0,
        uvLevel: 'low',
      },
    ],
  },
];

export default NARNIA;
